services:
  redis-app:
    container_name: redis-app
    image: redis:alpine
    command:
      [
        'redis-server',
        '--requirepass',
        '${REDIS_PASSWORD}',
        '--appendonly',
        'yes',
      ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512MB

  postgresql:
    container_name: postgresql
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256MB

  postgresql-adminer:
    container_name: medinven_adminer
    image: adminer
    restart: always
    ports:
    - '${ADMINER_PORT}:8080'
    networks:
    - app-network
    depends_on:
    - postgresql

     

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  postgresql-data:
    driver: local
